-
  version: 0.7.{build}
  image: Visual Studio 2019

  install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-29.0.3
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-29
  - dotnet tool install Cake.Tool --global --version 1.1.0

  branches:
    only:
      - publish

  only_commits:
    author: Piotr Szymczak

  build_script:
  - cmd: >-
      cd Build
  - cmd: >-
      dotnet cake .\build.cake --buildTarget=Publish-Packages --libVersion=0.7.0 
    
-
  version: 0.7.{build}
  image: Visual Studio 2019

  install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-29.0.3
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-29
  - dotnet tool install Cake.Tool --global --version 1.1.0

  build_script:
  - cmd: >-
      cd Build
  - cmd: >-
      dotnet cake .\build.cake --buildTarget=Test-All
