-
  version: 0.6.{build}
  image: Visual Studio 2017

  install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-27.0.3
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-27

  branches:
    only:
      - publish

  only_commits:
    author: Piotr Szymczak

  build_script:
  - cmd: >-
      cd Build
  - cmd: >-
      powershell .\build.ps1 -Verbosity diagnostic -ScriptArgs '-buildTarget="Publish-Packages"','-libVersion="0.7.0"' 
    
-
  version: 0.6.{build}
  image: Visual Studio 2017

  install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-27.0.3
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-27

  build_script:
  - cmd: >-
      cd Build
  - cmd: >-
      powershell .\build.ps1 -Verbosity diagnostic -ScriptArgs '-buildTarget="Test-All"'
