<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-android</TargetFramework>
        <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <!--
          Enable trim analyzers for Android class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>
    <ItemGroup>
      <AdditionalFiles Include="stylecop.json" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\AoLibs.Dialogs.Core\AoLibs.Dialogs.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.8.6" />
    </ItemGroup>
</Project>