site_name: AoLibs

nav:
  - Home: index.md
  - Installation: installation.md
  - About: about.md
  - Navigation: navigation.md
  - Android Navigation: navigation-android.md
  - iOS Navigation: navigation-ios.md
  - Adapters: adapters.md
  - Android Adapters: adapters-android.md
  - Android Recycler Adapters: android-recycler-adapters.md
  - AppVariables: app-variables.md
  - Utilities: utilities.md
  - Android Utilities: utilities-android.md
  - iOS Utilities: utilities-ios.md
  - Android Listeners: android-listeners.md
  - Android Layout to C#: android-layout-to-cs.md

extra_javascript:
    - js/hljs.js

extra_css:
    - css/default.css
    - css/extra.css

theme:
  name: material

markdown_extensions:
    - admonition
    - pymdownx.tasklist:
        custom_checkbox: true

copyright: 'Copyright &copy; 2018 Piotr Szymczak'

repo_name: 'Drutol/AoLibs'
repo_url: 'https://github.com/Drutol/AoLibs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Drutol/AoLibs'